#To catch value via @Value
build:
  version: "2.0"

#To catch properties via @configurationProperties
loans:
  message: "Hello from loans service from Zohair from prod environment"
  contactDetails:
    name: "John Doe - Prod"
    email: "aQ5eI_qa@example.com"
  onCallSupport:
    - 777-777-7777
    - 555-555-5555