services:
    accounts:
        image: "zohairtoo/accounts:s1"
        container_name: accounts-microservice
        ports:
            - "8080:8080"
        deploy:
          resources:
            limits:
              memory: 700m
        networks:
            - "zohairtoo"

    cards:
        image: "zohairtoo/cards:s1"
        container_name: cards-microservice
        ports:
            - "9000:9000"
        deploy:
          resources:
            limits:
              memory: 700m
        networks:
          - "zohairtoo"

    loans:
        image: "zohairtoo/loans:s1"
        container_name: loans-microservice
        ports:
            - "8090:8090"
        deploy:
          resources:
            limits:
              memory: 700m
        networks:
          - "zohairtoo"
networks:
  zohairtoo:
    driver: "bridge"