#To catch value via @Value
  build:
    version: "3.0"

  #To catch properties via @configurationProperties
  cards:
    message: "Hello from accounts service from Zohair"
    contactDetails:
      name: "John Doe - Developer"
      email: "aQ5eI@example.com"
    onCallSupport:
      - 777-777-7777
      - 555-555-5555